name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: "Update Submodules"
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: "Configure"
        run: |
          mkdir -p build
          cmake -B build

      - name: "Build"
        run: |
          make -C build

      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: led.uf2
          path: build/led.uf2
